documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 
      - 'package.json'
      - 'package-lock.json'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'frontend/**/*'
      - 'src/frontend/**/*'

backend:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - all-globs-to-all-files: '!src/frontend/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'
      - '**/*.test.ts'
      - '**/*.spec.ts'

database:
  - changed-files:
    - any-glob-to-any-file:
      - 'prisma/**/*'
      - '**/migrations/**/*'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'

kubernetes:
  - changed-files:
    - any-glob-to-any-file: 'k8s/**/*'
